INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
('WEAPON_PISTOL', 'Pistola', 20, 0, 1),
('WEAPON_ASSAULTRIFLE', 'Fucile Assalto', 2, 0, 1),
('WEAPON_PUMPSHOTGUN', 'Fucile a Pompa', 2, 0, 1),
('WEAPON_SMOKEGRENADE', 'Granata a gas', 25, 0, 1),
('WEAPON_MICROSMG', 'Micro SMG', 5, 0, 1),
('WEAPON_FLASHLIGHT', 'Torcia', 20, 0, 1),
('WEAPON_PETROLCAN', 'Tanica di benzina', 2, 0, 1),
('WEAPON_SMG', 'SMG', 2, 0, 1),
('WEAPON_CARBINERIFLE', 'Carabina Assalto', 2, 0, 1),
('WEAPON_MARKSMANRIFLE', 'Fucile da precisione', 2, 0, 1),
('WEAPON_NIGHTSTICK', 'Manganello', 10, 0, 1),
('WEAPON_COMBATPISTOL', 'Pistola da combattimento', 10, 0, 1),
('WEAPON_STUNGUN', 'Storditore', 10, 0, 1),
('WEAPON_BZGAS', 'BZGAS', 25, 0, 1),
('WEAPON_APPISTOL', 'Pistola AP', 10, 0, 1),
('WEAPON_PISTOL50', 'Pistola Calibro 50', 5, 0, 1),
('WEAPON_ASSAULTSMG', 'SMG Assalto', 2, 0, 1),
('WEAPON_VINTAGEPISTOL', 'Pistola Vintage', 15, 0, 1),
('WEAPON_MUSKET', 'Moschetto', 2, 0, 1),
('WEAPON_SPECIALCARBINE', 'Carabina Speciale', 2, 0, 1),
('WEAPON_SWITCHBLADE', 'Coltello a serramanico', 20, 0, 1),
('WEAPON_KNUCKLE', 'Torapugni', 20, 0, 1),
('WEAPON_SNSPISTOL', 'Pistola SNS', 15, 0, 1),
('mWEAPON_PISTOL', 'Munizioni Pistola', 1000, 0, 1),
('mWEAPON_ASSAULTRIFLE', 'Munizioni Fucile Assalto', 1000, 0, 1),
('mWEAPON_PUMPSHOTGUN', 'Munizioni Fucile a Pompa', 1000, 0, 1),
('mWEAPON_MICROSMG', 'Munizioni Micro SMG', 1000, 0, 1),
('mWEAPON_SMG', 'Munizioni SMG', 1000, 0, 1),
('mWEAPON_CARBINERIFLE', 'Munizioni Carabina Assalto', 1000, 0, 1),
('mWEAPON_MARKSMANRIFLE', 'Munizioni Fucile da precisione', 1000, 0, 1),
('mWEAPON_COMBATPISTOL', 'Munizioni Pistola da combattimento', 1000, 0, 1),
('mWEAPON_APPISTOL', 'Munizioni Pistola AP', 1000, 0, 1),
('mWEAPON_PISTOL50', 'Munizioni Pistola Calibro 50', 1000, 0, 1),
('mWEAPON_ASSAULTSMG', 'Munizioni SMG Assalto', 1000, 0, 1),
('mWEAPON_VINTAGEPISTOL', 'Munizioni Pistola Vintage', 1000, 0, 1),
('mWEAPON_MUSKET', 'Munizioni Moschetto', 1000, 0, 1),
('mWEAPON_SPECIALCARBINE', 'Munizioni Carabina Speciale', 1000, 0, 1),
('mWEAPON_SNSPISTOL', 'Munizioni Pistola SNS', 1000, 0, 1);



